# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate a quantitative trait under a Gaussian House-of-Cards mutation model
#' @param N The number of diploids
#' @param mu The mutation rate (per gamete, per generation)
#' @param sigmamu The standard deviation in the effect size of new mutations.  Mutation effect sizes ~ N(0,sigmamu^2).
#' @param sigmae The standard deviation in random effects added to phenotype
#' @param sigmas The standard deviation in the Gaussuian fitness function
#' @param ngens The number of generations to simulate
#' @return A matrix.  Columns 1 and 2 are the alleles for each diploid.  Column 3 is the random effect.  Phenotype is therefore given by rowSums(result)
#' @details  Tersely: the mutation model is Kingman's house-of-cards with Gaussian effects.  The inspiration for this function is Turelli.
#' @references Kingman, J. (1978). A simple model for the balance between selection and mutation. Journal of Applied Probability, 15, 1-12.
#' @references Turelli, M. (1984). Heritable genetic variation via mutation-selection balance: Lerch's zeta meets the abdominal bristle. Theoretical Population Biology, 25(2), 138-193.
#' @export
#' @examples
#' \dontrun{
#' N=5e2
#' mu=0.001
#' sige=0.15
#' sigmu=0.5
#' sigs=1
#' pop = HOCsim(N,mu,sigmu,sige,sigs,8*N)
#' }
HOCsim <- function(N, mu, sigmamu, sigmae, sigmas, ngens) {
    .Call('Rcode4teaching_HOCsim', PACKAGE = 'Rcode4teaching', N, mu, sigmamu, sigmae, sigmas, ngens)
}

#' Simulate a quantitative trait under an exponential House-of-Cards mutation model
#' @param N The number of diploids
#' @param mu The mutation rate (per gamete, per generation)
#' @param sigmamu The standard deviation in the effect size of new mutations.  Mutation effect sizes are exponentially-distributed with rate lambda = 1/sigmamu.
#' @param sigmae The standard deviation in random effects added to phenotype
#' @param sigmas The standard deviation in the Gaussuian fitness function
#' @param ngens The number of generations to simulate
#' @return A matrix.  Columns 1 and 2 are the alleles for each diploid.  Column 3 is the random effect.  Phenotype is therefore given by rowSums(result)
#' @references Kingman, J. (1978). A simple model for the balance between selection and mutation. Journal of Applied Probability, 15, 1-12.
#' @export
#' @examples
#' \dontrun{
#' N=5e2
#' mu=0.001
#' sige=0.15
#' sigmu=0.5
#' sigs=1
#' pop = HOCsim_exp(N,mu,sigmu,sige,sigs,8*N)
#' }
#' @export
HOCsim_exp <- function(N, mu, sigmamu, sigmae, sigmas, ngens) {
    .Call('Rcode4teaching_HOCsim_exp', PACKAGE = 'Rcode4teaching', N, mu, sigmamu, sigmae, sigmas, ngens)
}

VGVEdistHOC <- function(N, mu, sigmamu, sigmae, sigmas, ngens, nreps, gaussian = TRUE) {
    .Call('Rcode4teaching_VGVEdistHOC', PACKAGE = 'Rcode4teaching', N, mu, sigmamu, sigmae, sigmas, ngens, nreps, gaussian)
}

