# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
HOCsim <- function(N, mu, sigmamu, sigmae, sigmas, ngens) {
    .Call('Rcode4teaching_HOCsim', PACKAGE = 'Rcode4teaching', N, mu, sigmamu, sigmae, sigmas, ngens)
}

